main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.activity, name='activity'),
    path('delete/<str:pk>', views.delete, name='activityDelete'),
    path('delete/member/<str:pk>', views.deleteMember, name='memberDelete')
]

story6kybe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story7/', include('story7kybe.urls')),
    path('story8/', include('story8kybe.urls')),
    path('story9/', include('story9kybe.urls')),
]

story7kybe/urls.py
from django.urls import path

from . import views

app_name = 'story7kybe'

urlpatterns = [
    path('', views.home, name='home'),
]

story8kybe/urls.py
from django.urls import path
from .views import *

app_name = 'story8kybe'

urlpatterns = [
    path('', index, name='index'),
    path('data/', data, name='books_data')
]

story9kybe/urls.py
from django.urls import path
from . import views

app_name = 'story9kybe'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

main/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
    activity = models.CharField(max_length=100)
    def __str__(self):
        return self.activity

class Member(models.Model):
    member = models.CharField(max_length=100)
    aktivitas = models.ForeignKey(Activity, on_delete=models.CASCADE)
    def __str__(self):
        return self.member

story7kybe/models.py
from django.db import models

# Create your models here.

story8kybe/models.py
from django.db import models

# Create your models here.

story9kybe/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from .models import Activity, Member

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = '__all__'
        widgets = {
            'activity' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "masukan aktivitas"}),
        }

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'
        widgets = {
            'member' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "nama"}),
        }

story9kybe/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=30, required=False, help_text='Optional.')
    full_name = forms.CharField(max_length=30, required=False, help_text='Optional.')

    class Meta:
        model = User
        fields = ('username', 'full_name','email', 'password1', 'password2')

main/views.py
from django.shortcuts import render,redirect
from .models import Member, Activity
from .forms import MemberForm ,ActivityForm

# Create your views here.
def activity(request):
    if request.method == "POST":
        formA = ActivityForm(request.POST)
        formB = MemberForm(request.POST)
        if formA.is_valid():
            formA.save()
            return redirect('main:activity')
        elif formB.is_valid():
            formB.save()
            return redirect('main:activity')
        else:
            return redirect('main:activity')
    else:
        formA = ActivityForm()
        formB = MemberForm()
        activities = Activity.objects.all()
        members = Member.objects.all()
        context = {
            'formA' : formA,
            'formB' : formB,
            'activities' : activities,
            'members' : members
        }
        return render(request, 'main/home.html', context)

def delete(request,pk):
    activity = Activity.objects.get(id=pk)
    activity.delete()
    return redirect('main:activity')

def deleteMember(request,pk):
    member = Member.objects.get(id=pk)
    member.delete()
    return redirect('main:activity')

story7kybe/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'story7.html')

story8kybe/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
import requests

# Create your views here.
def index(request):
    return render(request, 'books.html')

def data(request):
    try:
        q = request.GET['q']
    except:
        q = "quilting"
    
    json_read = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + q).json()

    return JsonResponse(json_read)

story9kybe/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout


# Create your views here.
def index(request):
    return render(request, 'story9.html')

def login(request):
    if request.method == 'POST': 
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            messages.success(request, 'Logged in as {}'.format(username))
            return redirect('/story9')
        else:
            messages.warning(request, 'Username or password is incorrect')
    return render(request, 'login.html')

def logout(request):
    auth_logout(request)
    messages.success(request, 'Successfully logged out!')
    return redirect('/story9')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            auth_login(request, user)
            messages.success(request, "Successfully created a user with username {}".format(username))
            return redirect('/story9')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form' : form})

main/templates/main/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container py-4">
        
    <h1 class="display-4 text-center pb-4 border-bottom" style:margin-top:20px></h1>
    <Form method="POST" class="row my-5">
        {% csrf_token %}
        <div class="col-7 ml-auto">
            {{ formA.activity }}
        </div>
        <button type="submit" class="btn col-2 mr-auto">Tambah</button>
    </Form>
    <hr>
    <div class="d-flex justify-content-around flex-wrap pb-4">
        {% for activity in activities %}
        <div class="card bg-light mt-5" style="width: 18rem;">
            <div class="card-header">
                <div class="row">
                    <h5 class="col-10 mb-2">{{ activity }}</h5>
                    <a href="{% url 'main:activityDelete' activity.id %}" class="col-2">
                        <button type="button" class="close mb-2">&times;</button>
                    </a>
                </div>
            </div>
            <div class="card-body">
                <h6 class="card-title">Anggota:</h6>
                <p></p>
                <ul>

                    {% for member in members %}
                    {% if member.aktivitas.id == activity.id %}
                    <li class="row">
                        <h5 class="col-10">{{ member }}</h5>
                        <a href="{% url 'main:memberDelete' member.id %}" class="col-2">
                            <button type="button" class="close">&times;</button>
                        </a>    
                    </li>
                    {% endif %}
                    {% endfor %}

                </ul>
                <form method="POST">
                    {% csrf_token %}
                    {{ formB.member }}
                    <input name="aktivitas" type="text" value="{{ activity.id }}" style="display: none;">
                    <button type="submit" class="btn col-6 mt-2">Ikuti</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

story7kybe/templates/story7.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 7 kybe</title>
{% endblock meta %}
{% block content %}

<div class="container" id="container">
  <div class="row" id="judul">
    <h1>Halo,<br>
    Saya Rizky<br>
    Berikut adalah informasi mengenai saya</h1>
  </div>
  <div id="accordion">
    <div class="group" data-sort="0">
      <div id="head">
        <p> Profil Saya
          <button class="sort-up"><img src="{% static 'img/chevron-up.svg' %}"></button> 
          <button class="sort-down"><img src="{% static 'img/chevron-down.svg' %}"></button>
        </p>
      </div>
      <div id="content">
        <p>
          Halo, perkenalkan saya Rizky Pratama Nataprawira atau biasa dipanggil Kybe. 
          Saat ini saya merupakan mahasiswa tingkat 2 Sistem Informasi di Fakultas Ilmu Komputer Universitas Indonesia. 
        </p>
      </div>
    </div>

    <div class="group" data-sort="1">
      <div id="head">
        <p> aktivitas saat ini
          <button class="sort-up"><img src="{% static 'img/chevron-up.svg' %}"></button> 
          <button class="sort-down"><img src="{% static 'img/chevron-down.svg' %}"></button>
        </p>
      </div>
      <div id="content">
        <p>
          Untuk saat ini, kesibukan saya adalah kuliah dan beberapa kepanitiaan.
        </p>
      </div>
    </div>

    <div class="group" data-sort="2">
      <div id="head">
        <p> pengalaman kepantian
          <button class="sort-up"><img src="{% static 'img/chevron-up.svg' %}"></button> 
          <button class="sort-down"><img src="{% static 'img/chevron-down.svg' %}"></button>
        <p>
      </div>
      <div id="content">
        <p>
          <b>Compfest</b><br>
          Staff of Fundraising (Feb 2020 - Sekarang)<br>
          <b>PMB Fasilkom</b><br>
          Staff of Event (Jul 2020 - Sekarang)
        </p>
      </div>
    </div>

    <div class="group" data-sort="3">
      <div id="head">
        <p> Prestasi
          <button class="sort-up"><img src="{% static 'img/chevron-up.svg' %}"></button> 
          <button class="sort-down"><img src="{% static 'img/chevron-down.svg' %}"></button>
        <p>
      </div>
      <div id="content"><p>Prestasi terbesar saya saat ini adalah dapat masuk dan bertahan di Fasilkom UI hingga sekarang</p></div>
    </div>

  </div>
  
</div>
{% endblock content %}

story8kybe/templates/books.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class='container'>
    <h3 style ="margin-top: 1vh;">Cari Buku</h3>
    <div class="input">
        <input type="text" id="input" placeholder="cari">
    </div>
    <br>
    <div class="content">
        <table class= "table table-borderless">
            <thead>
                <tr>
                    <th scope="col" class="align-middle">no</th>
                    <th scope="col" class="align-middle">cover</th>
                    <th scope="col" class="align-middle">title</th>
                    <th scope="col" class="align-middle">authors</th>
                    <th scope="col" class="align-middle">publisher</th>
                    <th scope="col" class="align-middle">published date</th>
                </tr>
            </thead>
            <tbody id="konten"></tbody>
        </table>
    </div>
</div>


{% endblock content %}

story9kybe/templates/login.html
{% include "base.html" %} 
{% block content %}
<div class="container">
<h1 style="text-align: center;">login</h1>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
{{ message }}
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
</div>
{% endfor %}
{% endif %}
<div style="text-align: center;">
    <form action="" method="POST">
        {% csrf_token %}
        <p>username: </p><input type="text" name="username">
        <p>password: </p><input type="password" name="password">
        <br>
        <br>
        <button class="submit" type="submit">login</button>
    </form>
    <br>
    <a href= "/story9"><button>kembali</button></a>
</div>
</div>
{% endblock content %}

story9kybe/templates/signup.html
{% load static %}
{% include "base.html" %} 
{% block content %}
<h1 class="title" style="text-align: center;">sign up</h1>
<div style="margin-left: 5vw;">
  <form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="submit" type="submit">Submit</button>
  </form>
</div>

{% endblock content %}

story9kybe/templates/story9.html
<!DOCTYPE html>
{% load static %}
{% include "base.html" %} 
{% block content %}
<div class="container" style="margin-left: auto;">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
    {% endfor %}
    {% endif %}
    <div>
        {% if user.is_authenticated %}
        <h1 style="text-align: center;">Selamat Datang {{ user }}</h1>
    </div>
    <div id= "logout" style="text-align: center;">
        <a href= "/story9/logout"><button  style="color: #444; font-size: large;">logout</button></a>
    </div>
    {% else %}
    <h1 style="text-align: center;">Selamat Datang</h1>
    <div class="container" style="margin-top: 5vh;text-align: center;">
        <a href= "/story9/login" ><button style="color: #444;font-size: xx-large">login</button></a>
        <a href= "/story9/signup"><button style="color: #444;;font-size: xx-large">sign up</button></a>
    </div>
    {% endif %}
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>KYBE</title>
    <nav class="nav">
      <div class="navbar-brand">Rizky Pratama</div>
      <a class="nav-link"  href="{% url 'main:activity' %}">story6</a>
      <a class="nav-link"  href="{% url 'story7kybe:home' %}">story7</a>
      <a class="nav-link"  href="{% url 'story8kybe:index' %}">story8</a>
      <a class="nav-link"  href="{% url 'story9kybe:index' %}">story9</a>
    </nav>

</head>
<body style="background-color: #EDF2F4;">
    {% block content%}
    
    {% endblock content%}
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/ok.js' %}"></script>
    <script src="{% static 'js/story8.js' %}"></script>
  </body>
</html>